# Generated by Django 3.1.5 on 2021-01-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.CharField(choices=[('1', 'Non Inclusif'), ('2', 'Inclusif'), ('0', 'Non Applicable')], max_length=20),
        ),
    ]
