# Generated by Django 3.1.5 on 2021-01-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0003_auto_20210121_0718'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('word', 'position', 'sentence')},
        ),
    ]
