# Generated by Django 3.1.5 on 2021-01-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0004_auto_20210121_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='verdict',
            field=models.CharField(blank=True, choices=[('conflict', 'conflict'), ('1', 'Non Inclusif'), ('2', 'Inclusif'), ('0', 'Non Applicable')], max_length=100, null=True),
        ),
    ]
