# Generated by Django 3.1.5 on 2021-01-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0006_auto_20210121_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_na',
        ),
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.CharField(choices=[('1', 'Non Inclusif'), ('2', 'Inclusif'), ('0', 'Non Applicable')], max_length=20),
        ),
    ]
