# Generated by Django 3.1.5 on 2021-02-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0008_sentence_sentenceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.CharField(choices=[('3', 'Epicène'), ('1', 'Non Inclusif'), ('2', 'Inclusif'), ('0', 'Non Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='word',
            name='verdict',
            field=models.CharField(blank=True, choices=[('3', 'Epicène'), ('conflict', 'conflict'), ('1', 'Non Inclusif'), ('2', 'Inclusif'), ('0', 'Non Applicable')], max_length=100, null=True),
        ),
    ]
