# Generated by Django 3.1.5 on 2021-02-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifyme', '0010_auto_20210223_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.CharField(choices=[('1', 'Non Inclusif'), ('2', 'Inclusif'), ('0', 'Non Applicable'), ('3', 'Epicène')], max_length=20),
        ),
    ]
